### ISSUE TITLE
[FEATURE] Option to 'Keep line breaks' to improve readability.

### ISSUE THREAD

**Issue by codey-badger** [StrangeGirlMurph/obsidian-wikipedia-search#37] opened 2024-09-12 22:56 UTC
First, Thanks for your awesome work and openness to improve!

# Description of the Problem
Often when I'm creating or linking articles in my Vault I notice myself manually inserting new lines in the big paragraph (obtained with the tag {intro} ) to improve readability. This is specially necessary using a mobile device. 

# Description of the Solution
Option to 'Keep line breaks' or Ideally it would be part of the default 'auto-cleanup of intros' but any other way to accomplish it's welcome. 

If you got time, tell me if this can be possible or maybe it could  break the 'auto-cleanup of intros'?

**Expected behaviour**
Intro of Total Order article with line breaks: 
 ```
In mathematics, a total order or linear order is a partial order in which any two elements are comparable. That is, a total order is a binary relation $\leq$ on some set $X$, which satisfies the following for all $a,b$ and $c$ in $X$:

$a\leq a$ (reflexive).
If $a\leq b$ and $b\leq c$ then $a\leq c$ (transitive).
If $a\leq b$ and $b\leq a$ then $a=b$ (antisymmetric).
$a\leq b$ or $b\leq a$ (strongly connected, formerly called total).

Reflexivity (1.) already follows from connectedness (4.), but is required explicitly by many authors nevertheless, to indicate the kinship to partial orders.
Total orders are sometimes also called simple, connex, or full orders.

A set equipped with a total order is a totally ordered set; the terms simply ordered set, linearly ordered set, and loset are also used. The term chain is sometimes defined as a synonym of totally ordered set, but refers generally to some sort of totally ordered subsets of a given partially ordered set.

An extension of a given partial order to a total order is called a linear extension of that partial order.
```

**Current behaviour**
Intro of Total Order article: 
```
In mathematics, a total order or linear order is a partial order in which any two elements are comparable. That is, a total order is a binary relation $\leq$ on some set $X$, which satisfies the following for all $a,b$ and $c$ in $X$:
$a\leq a$ (reflexive).
If $a\leq b$ and $b\leq c$ then $a\leq c$ (transitive).
If $a\leq b$ and $b\leq a$ then $a=b$ (antisymmetric).
$a\leq b$ or $b\leq a$ (strongly connected, formerly called total).
Reflexivity (1.) already follows from connectedness (4.), but is required explicitly by many authors nevertheless, to indicate the kinship to partial orders.
Total orders are sometimes also called simple, connex, or full orders.
A set equipped with a total order is a totally ordered set; the terms simply ordered set, linearly ordered set, and loset are also used. The term chain is sometimes defined as a synonym of totally ordered set, but refers generally to some sort of totally ordered subsets of a given partially ordered set.
An extension of a given partial order to a total order is called a linear extension of that partial order.
```
# Additional
I was thinking maybe this would work but it didn't after changing the code manually using my phone.
 
```js
// Turns all "{\displaystyle ...}" occurrences into a proper LaTeX equation
.replaceAll(/{\\displaystyle [^\n]+}/g, (text: string) => "$" + text.slice(15, -1).trim() + "$")
// Keeps double line breaks for paragraph separation
.replaceAll(/\n{2,}/g, '\n\n')
// Replaces single line breaks within paragraphs with a space
.replaceAll(/\n(?!\n)/g, ' ')
// Takes care of extra spaces
.replaceAll("  ", " ") 
// Escapes backticks to avoid conflicts with markdown syntax
.replaceAll("`", "\\`")
```

**Comment by StrangeGirlMurph** [comment] 2024-09-13 07:52
Hey :) You're welcome! The work is really fun and I love getting feedback and improving the plugin.

Now to the line breaks. Sadly this doesn't work :( The Wikipedia API just collapses those paragraphs into a single line break.

This is what the API returns: `"In mathematics, a total order or linear order is a partial order in which any two elements are comparable.  That is, a total order is a binary relation \n  \n    \n      \n        ≤\n      \n    \n    {\\displaystyle \\leq }\n  \n on some set \n  \n    \n      \n        X\n      \n    \n    {\\displaystyle X}\n  \n, which satisfies the following for all \n  \n    \n      \n        a\n        ,\n        b\n      \n    \n    {\\displaystyle a,b}\n  \n and \n  \n    \n      \n        c\n      \n    \n    {\\displaystyle c}\n  \n in \n  \n    \n      \n        X\n      \n    \n    {\\displaystyle X}\n  \n:\n\n  \n    \n      \n        a\n        ≤\n        a\n      \n    \n    {\\displaystyle a\\leq a}\n  \n (reflexive).\nIf \n  \n    \n      \n        a\n        ≤\n        b\n      \n    \n    {\\displaystyle a\\leq b}\n  \n and \n  \n    \n      \n        b\n        ≤\n        c\n      \n    \n    {\\displaystyle b\\leq c}\n  \n then \n  \n    \n      \n        a\n        ≤\n        c\n      \n    \n    {\\displaystyle a\\leq c}\n  \n (transitive).\nIf \n  \n    \n      \n        a\n        ≤\n        b\n      \n    \n    {\\displaystyle a\\leq b}\n  \n and \n  \n    \n      \n        b\n        ≤\n        a\n      \n    \n    {\\displaystyle b\\leq a}\n  \n then \n  \n    \n      \n        a\n        =\n        b\n      \n    \n    {\\displaystyle a=b}\n  \n (antisymmetric).\n\n  \n    \n      \n        a\n        ≤\n        b\n      \n    \n    {\\displaystyle a\\leq b}\n  \n or \n  \n    \n      \n        b\n        ≤\n        a\n      \n    \n    {\\displaystyle b\\leq a}\n  \n (strongly connected, formerly called total).\nReflexivity (1.) already follows from connectedness (4.), but is required explicitly by many authors nevertheless, to indicate the kinship to partial orders.\nTotal orders are sometimes also called simple, connex, or full orders.\nA set equipped with a total order is a totally ordered set; the terms simply ordered set, linearly ordered set, and loset are also used. The term chain is sometimes defined as a synonym of totally ordered set, but refers generally to some sort of totally ordered subsets of a given partially ordered set.\nAn extension of a given partial order to a total order is called a linear extension of that partial order.\n\n"`

As you can see between "... or full orders." and "A set equipped ..." the is a single line break at the position you would like to have  a double line break to format paragraphs better. The problem is between the list items (reflexive, transitive, antisymmetric, total) there are also just single line breaks (in this case hard to see bc of all the messy latex stuff). In general I just can't distinguish these two cases in the code where in one case we want a single line break to stay that way (the list) and in other cases a single line break should be converted to two line breaks to separate paragraphs. 

I hope this makes sense. Please feel free to continue asking questions even after I closed this.

**Closed by StrangeGirlMurph** 2024-09-13 07:52 UTC
Labels: enhancement
